const TELNET_TIMEOUT = 5000;
const MEMCACHED_CONNECT_TIMEOUT_SECONDS = 10;
const MEMCACHED_KEEPALIVE_DELAY_SECONDS = 30;
const MAX_CONCURRENT_REQUESTS = 100;
const ONE_MINUTE_IN_SECONDS = 60;
const ONE_DAY_IN_SECONDS = 86400;
const MEMCACHED_MAX_VALUE_BYTES = 1024 * 1024;
const RESERVED_KEYS = {
  INDEXES: "__MEM_INDEXES__",
  SHARD_PREFIX: "__MEM_INDEX_",
  SHARD_SUFFIX: "__"
} as const;

const isReservedKey = (key: string) =>
  key === RESERVED_KEYS.INDEXES || key.startsWith(RESERVED_KEYS.SHARD_PREFIX);

export {
  TELNET_TIMEOUT,
  MEMCACHED_CONNECT_TIMEOUT_SECONDS,
  MEMCACHED_KEEPALIVE_DELAY_SECONDS,
  MAX_CONCURRENT_REQUESTS,
  ONE_MINUTE_IN_SECONDS,
  ONE_DAY_IN_SECONDS,
  MEMCACHED_MAX_VALUE_BYTES,
  RESERVED_KEYS,
  isReservedKey
};
