const TELNET_TIMEOUT = 5000;
const MAX_CONCURRENT_REQUESTS = 100;
const ONE_DAY_IN_SECONDS = 86400;
const RESERVED_KEY = "__ALL_KEYS__";

export {
  TELNET_TIMEOUT,
  MAX_CONCURRENT_REQUESTS,
  ONE_DAY_IN_SECONDS,
  RESERVED_KEY
};
